return {
--   "MeanderingProgrammer/render-markdown.nvim",
--   -- 👇 依赖项：必须安装 Treesitter 和 图标库
--   dependencies = { 
--     "nvim-treesitter/nvim-treesitter", 
--     "nvim-tree/nvim-web-devicons" 
--   },
--   -- 👇 关键配置：只有在打开 markdown 或 Avante 窗口时才加载插件
--   ft = { "markdown", "Avante" },
--   opts = {
--     -- 这里可以放自定义配置，如果习惯默认风格，留空即可
--     -- 例如：自定义代码块背景色等
--     code = {
--       sign = true, -- 在代码块左侧显示图标
--       width = 'block', -- 代码块背景宽度
--       --border_pad = [1,1,1,1], -- 内边距
--     },
--     heading = {
--       sign = true, -- 标题显示图标
--       icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " }, -- 自定义标题图标
--     },
--   },
}
